[2025-07-01T22:56:02.246+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T22:56:02.304+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:54:00+00:00 [queued]>
[2025-07-01T22:56:02.319+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:54:00+00:00 [queued]>
[2025-07-01T22:56:02.320+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-01T22:56:02.351+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_run_silver> on 2025-07-01 22:54:00+00:00
[2025-07-01T22:56:02.361+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=452) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T22:56:02.362+0000] {standard_task_runner.py:64} INFO - Started process 453 to run task
[2025-07-01T22:56:02.367+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_trino_silver_pipeline', 'dbt_run_silver', 'scheduled__2025-07-01T22:54:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/dbt_trino_silver_dag.py', '--cfg-path', '/tmp/tmprleujwor']
[2025-07-01T22:56:02.370+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask dbt_run_silver
[2025-07-01T22:56:02.504+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:54:00+00:00 [running]> on host 0a4aae371d36
[2025-07-01T22:56:02.653+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='dbt_trino_silver_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T22:54:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T22:54:00+00:00'
[2025-07-01T22:56:02.654+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T22:56:02.725+0000] {docker.py:367} INFO - Starting docker container from image modern-data-pipeline-dbt-trino:latest
[2025-07-01T22:56:03.213+0000] {docker.py:438} INFO - === Executando dbt run incremental ===
[2025-07-01T22:56:07.475+0000] {docker.py:438} INFO - [0m22:56:07  Running with dbt=1.7.0
[2025-07-01T22:56:08.102+0000] {docker.py:438} INFO - [0m22:56:08  Registered adapter: trino=1.7.0
[2025-07-01T22:56:08.237+0000] {docker.py:438} INFO - [0m22:56:08  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-07-01T22:56:08.238+0000] {docker.py:438} INFO - There are 2 unused configuration paths:
[2025-07-01T22:56:08.238+0000] {docker.py:438} INFO - - seeds.agronegocio_iceberg
[2025-07-01T22:56:08.238+0000] {docker.py:438} INFO - - snapshots.agronegocio_iceberg
[2025-07-01T22:56:08.273+0000] {docker.py:438} INFO - [0m22:56:08  Found 1 model, 29 tests, 5 operations, 1 source, 0 exposures, 0 metrics, 541 macros, 0 groups, 0 semantic models
[2025-07-01T22:56:08.276+0000] {docker.py:438} INFO - [0m22:56:08
[2025-07-01T22:56:08.799+0000] {docker.py:438} INFO - [0m22:56:08
[2025-07-01T22:56:08.800+0000] {docker.py:438} INFO - [0m22:56:08  Running 4 on-run-start hooks
[2025-07-01T22:56:08.809+0000] {docker.py:438} INFO - [0m22:56:08  Iniciando execuÃ§Ã£o do dbt com Trino/Iceberg
[2025-07-01T22:56:08.819+0000] {docker.py:438} INFO - [0m22:56:08  1 of 4 START hook: agronegocio_iceberg.on-run-start.0 .......................... [RUN]
[2025-07-01T22:56:08.822+0000] {docker.py:438} INFO - [0m22:56:08  1 of 4 OK hook: agronegocio_iceberg.on-run-start.0 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T22:56:08.831+0000] {docker.py:438} INFO - [0m22:56:08  2 of 4 START hook: agronegocio_iceberg.on-run-start.1 .......................... [RUN]
[2025-07-01T22:56:08.937+0000] {docker.py:438} INFO - [0m22:56:08  2 of 4 OK hook: agronegocio_iceberg.on-run-start.1 ............................. [[32mSUCCESS[0m in 0.10s]
[2025-07-01T22:56:08.946+0000] {docker.py:438} INFO - [0m22:56:08  3 of 4 START hook: agronegocio_iceberg.on-run-start.2 .......................... [RUN]
[2025-07-01T22:56:08.999+0000] {docker.py:438} INFO - [0m22:56:08  3 of 4 OK hook: agronegocio_iceberg.on-run-start.2 ............................. [[32mSUCCESS[0m in 0.05s]
[2025-07-01T22:56:09.007+0000] {docker.py:438} INFO - [0m22:56:09  4 of 4 START hook: agronegocio_iceberg.on-run-start.3 .......................... [RUN]
[2025-07-01T22:56:09.047+0000] {docker.py:438} INFO - [0m22:56:09  4 of 4 OK hook: agronegocio_iceberg.on-run-start.3 ............................. [[32mSUCCESS[0m in 0.04s]
[2025-07-01T22:56:09.048+0000] {docker.py:438} INFO - [0m22:56:09
[2025-07-01T22:56:09.052+0000] {docker.py:438} INFO - [0m22:56:09  Concurrency: 2 threads (target='dev')
[2025-07-01T22:56:09.053+0000] {docker.py:438} INFO - [0m22:56:09
[2025-07-01T22:56:09.070+0000] {docker.py:438} INFO - [0m22:56:09  1 of 1 START sql incremental model silver.silver_dados_produtores_agro_trino ... [RUN]
[2025-07-01T22:56:09.214+0000] {docker.py:438} INFO - [0m22:56:09  1 of 1 ERROR creating sql incremental model silver.silver_dados_produtores_agro_trino  [[31mERROR[0m in 0.14s]
[2025-07-01T22:56:09.219+0000] {docker.py:438} INFO - [0m22:56:09
[2025-07-01T22:56:09.221+0000] {docker.py:438} INFO - [0m22:56:09  Running 1 on-run-end hook
[2025-07-01T22:56:09.230+0000] {docker.py:438} INFO - [0m22:56:09  ExecuÃ§Ã£o finalizada
[2025-07-01T22:56:09.233+0000] {docker.py:438} INFO - [0m22:56:09  1 of 1 START hook: agronegocio_iceberg.on-run-end.0 ............................ [RUN]
[2025-07-01T22:56:09.234+0000] {docker.py:438} INFO - [0m22:56:09  1 of 1 OK hook: agronegocio_iceberg.on-run-end.0 ............................... [[32mOK[0m in 0.00s]
[2025-07-01T22:56:09.235+0000] {docker.py:438} INFO - [0m22:56:09
[2025-07-01T22:56:09.238+0000] {docker.py:438} INFO - [0m22:56:09
[2025-07-01T22:56:09.240+0000] {docker.py:438} INFO - [0m22:56:09  Finished running 1 incremental model, 5 hooks in 0 hours 0 minutes and 0.96 seconds (0.96s).
[2025-07-01T22:56:09.268+0000] {docker.py:438} INFO - [0m22:56:09
[2025-07-01T22:56:09.270+0000] {docker.py:438} INFO - [0m22:56:09  [31mCompleted with 1 error and 0 warnings:[0m
[2025-07-01T22:56:09.271+0000] {docker.py:438} INFO - [0m22:56:09
[2025-07-01T22:56:09.273+0000] {docker.py:438} INFO - [0m22:56:09    Compilation Error in model silver_dados_produtores_agro_trino (models/silver/silver_dados_produtores_agro_trino.sql)
[2025-07-01T22:56:09.273+0000] {docker.py:438} INFO -   Object of type date is not JSON serializable
[2025-07-01T22:56:09.273+0000] {docker.py:438} INFO -   
[2025-07-01T22:56:09.274+0000] {docker.py:438} INFO -   > in macro run_hooks (macros/materializations/hooks.sql)
[2025-07-01T22:56:09.274+0000] {docker.py:438} INFO -   > called by macro materialization_incremental_trino (macros/materializations/incremental.sql)
[2025-07-01T22:56:09.274+0000] {docker.py:438} INFO -   > called by model silver_dados_produtores_agro_trino (models/silver/silver_dados_produtores_agro_trino.sql)
[2025-07-01T22:56:09.276+0000] {docker.py:438} INFO - [0m22:56:09
[2025-07-01T22:56:09.277+0000] {docker.py:438} INFO - [0m22:56:09  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-07-01T22:56:10.439+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T22:56:10.450+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T22:56:10.457+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_trino_silver_pipeline, task_id=dbt_run_silver, run_id=scheduled__2025-07-01T22:54:00+00:00, execution_date=20250701T225400, start_date=20250701T225602, end_date=20250701T225610
[2025-07-01T22:56:10.475+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 61 for task dbt_run_silver (Docker container failed: {'StatusCode': 1}; 453)
[2025-07-01T22:56:10.499+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-01T22:56:10.533+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T22:56:10.538+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
