[2025-07-01T22:54:01.832+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-01T22:54:01.884+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:52:00+00:00 [queued]>
[2025-07-01T22:54:01.901+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:52:00+00:00 [queued]>
[2025-07-01T22:54:01.902+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-01T22:54:01.919+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): dbt_run_silver> on 2025-07-01 22:52:00+00:00
[2025-07-01T22:54:01.929+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=412) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-01T22:54:01.929+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_trino_silver_pipeline', 'dbt_run_silver', 'scheduled__2025-07-01T22:52:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/dbt_trino_silver_dag.py', '--cfg-path', '/tmp/tmp2f1wb8zl']
[2025-07-01T22:54:01.931+0000] {standard_task_runner.py:91} INFO - Job 59: Subtask dbt_run_silver
[2025-07-01T22:54:01.931+0000] {standard_task_runner.py:64} INFO - Started process 413 to run task
[2025-07-01T22:54:02.006+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_trino_silver_pipeline.dbt_run_silver scheduled__2025-07-01T22:52:00+00:00 [running]> on host 0a4aae371d36
[2025-07-01T22:54:02.130+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@example.com' AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='dbt_trino_silver_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run_silver' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T22:52:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T22:52:00+00:00'
[2025-07-01T22:54:02.131+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-01T22:54:02.182+0000] {docker.py:367} INFO - Starting docker container from image modern-data-pipeline-dbt-trino:latest
[2025-07-01T22:54:02.539+0000] {docker.py:438} INFO - === Executando dbt run incremental ===
[2025-07-01T22:54:05.727+0000] {docker.py:438} INFO - [0m22:54:05  Running with dbt=1.7.0
[2025-07-01T22:54:06.261+0000] {docker.py:438} INFO - [0m22:54:06  Registered adapter: trino=1.7.0
[2025-07-01T22:54:06.295+0000] {docker.py:438} INFO - [0m22:54:06  Unable to do partial parsing because a project config has changed
[2025-07-01T22:54:08.027+0000] {docker.py:438} INFO - [0m22:54:08  Iniciando execuÃ§Ã£o do dbt com Trino/Iceberg
[2025-07-01T22:54:08.051+0000] {docker.py:438} INFO - [0m22:54:08  ExecuÃ§Ã£o finalizada
[2025-07-01T22:54:08.594+0000] {docker.py:438} INFO - [0m22:54:08  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-07-01T22:54:08.594+0000] {docker.py:438} INFO - There are 2 unused configuration paths:
[2025-07-01T22:54:08.595+0000] {docker.py:438} INFO - - seeds.agronegocio_iceberg
[2025-07-01T22:54:08.595+0000] {docker.py:438} INFO - - snapshots.agronegocio_iceberg
[2025-07-01T22:54:08.618+0000] {docker.py:438} INFO - [0m22:54:08  Found 1 model, 29 tests, 5 operations, 1 source, 0 exposures, 0 metrics, 541 macros, 0 groups, 0 semantic models
[2025-07-01T22:54:08.620+0000] {docker.py:438} INFO - [0m22:54:08
[2025-07-01T22:54:10.394+0000] {docker.py:438} INFO - [0m22:54:10
[2025-07-01T22:54:10.394+0000] {docker.py:438} INFO - [0m22:54:10  Running 4 on-run-start hooks
[2025-07-01T22:54:10.399+0000] {docker.py:438} INFO - [0m22:54:10  Iniciando execuÃ§Ã£o do dbt com Trino/Iceberg
[2025-07-01T22:54:10.404+0000] {docker.py:438} INFO - [0m22:54:10  1 of 4 START hook: agronegocio_iceberg.on-run-start.0 .......................... [RUN]
[2025-07-01T22:54:10.405+0000] {docker.py:438} INFO - [0m22:54:10  1 of 4 OK hook: agronegocio_iceberg.on-run-start.0 ............................. [[32mOK[0m in 0.00s]
[2025-07-01T22:54:10.410+0000] {docker.py:438} INFO - [0m22:54:10  2 of 4 START hook: agronegocio_iceberg.on-run-start.1 .......................... [RUN]
[2025-07-01T22:54:10.457+0000] {docker.py:438} INFO - [0m22:54:10  2 of 4 OK hook: agronegocio_iceberg.on-run-start.1 ............................. [[32mSUCCESS[0m in 0.05s]
[2025-07-01T22:54:10.462+0000] {docker.py:438} INFO - [0m22:54:10  3 of 4 START hook: agronegocio_iceberg.on-run-start.2 .......................... [RUN]
[2025-07-01T22:54:10.487+0000] {docker.py:438} INFO - [0m22:54:10  3 of 4 OK hook: agronegocio_iceberg.on-run-start.2 ............................. [[32mSUCCESS[0m in 0.02s]
[2025-07-01T22:54:10.491+0000] {docker.py:438} INFO - [0m22:54:10  4 of 4 START hook: agronegocio_iceberg.on-run-start.3 .......................... [RUN]
[2025-07-01T22:54:10.708+0000] {docker.py:438} INFO - [0m22:54:10  4 of 4 OK hook: agronegocio_iceberg.on-run-start.3 ............................. [[32mSUCCESS[0m in 0.22s]
[2025-07-01T22:54:10.708+0000] {docker.py:438} INFO - [0m22:54:10
[2025-07-01T22:54:10.710+0000] {docker.py:438} INFO - [0m22:54:10  Concurrency: 2 threads (target='dev')
[2025-07-01T22:54:10.711+0000] {docker.py:438} INFO - [0m22:54:10
[2025-07-01T22:54:10.721+0000] {docker.py:438} INFO - [0m22:54:10  1 of 1 START sql incremental model silver.silver_dados_produtores_agro_trino ... [RUN]
[2025-07-01T22:54:10.795+0000] {docker.py:438} INFO - [0m22:54:10  1 of 1 ERROR creating sql incremental model silver.silver_dados_produtores_agro_trino  [[31mERROR[0m in 0.07s]
[2025-07-01T22:54:10.799+0000] {docker.py:438} INFO - [0m22:54:10
[2025-07-01T22:54:10.799+0000] {docker.py:438} INFO - [0m22:54:10  Running 1 on-run-end hook
[2025-07-01T22:54:10.807+0000] {docker.py:438} INFO - [0m22:54:10  ExecuÃ§Ã£o finalizada
[2025-07-01T22:54:10.808+0000] {docker.py:438} INFO - [0m22:54:10  1 of 1 START hook: agronegocio_iceberg.on-run-end.0 ............................ [RUN]
[2025-07-01T22:54:10.809+0000] {docker.py:438} INFO - [0m22:54:10  1 of 1 OK hook: agronegocio_iceberg.on-run-end.0 ............................... [[32mOK[0m in 0.00s]
[2025-07-01T22:54:10.809+0000] {docker.py:438} INFO - [0m22:54:10
[2025-07-01T22:54:10.811+0000] {docker.py:438} INFO - [0m22:54:10
[2025-07-01T22:54:10.812+0000] {docker.py:438} INFO - [0m22:54:10  Finished running 1 incremental model, 5 hooks in 0 hours 0 minutes and 2.19 seconds (2.19s).
[2025-07-01T22:54:10.828+0000] {docker.py:438} INFO - [0m22:54:10
[2025-07-01T22:54:10.828+0000] {docker.py:438} INFO - [0m22:54:10  [31mCompleted with 1 error and 0 warnings:[0m
[2025-07-01T22:54:10.829+0000] {docker.py:438} INFO - [0m22:54:10
[2025-07-01T22:54:10.830+0000] {docker.py:438} INFO - [0m22:54:10    Compilation Error in model silver_dados_produtores_agro_trino (models/silver/silver_dados_produtores_agro_trino.sql)
[2025-07-01T22:54:10.830+0000] {docker.py:438} INFO -   Object of type date is not JSON serializable
[2025-07-01T22:54:10.830+0000] {docker.py:438} INFO -   
[2025-07-01T22:54:10.831+0000] {docker.py:438} INFO -   > in macro run_hooks (macros/materializations/hooks.sql)
[2025-07-01T22:54:10.831+0000] {docker.py:438} INFO -   > called by macro materialization_incremental_trino (macros/materializations/incremental.sql)
[2025-07-01T22:54:10.831+0000] {docker.py:438} INFO -   > called by model silver_dados_produtores_agro_trino (models/silver/silver_dados_produtores_agro_trino.sql)
[2025-07-01T22:54:10.832+0000] {docker.py:438} INFO - [0m22:54:10
[2025-07-01T22:54:10.832+0000] {docker.py:438} INFO - [0m22:54:10  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-07-01T22:54:11.974+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-01T22:54:11.988+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 460, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-07-01T22:54:11.998+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_trino_silver_pipeline, task_id=dbt_run_silver, run_id=scheduled__2025-07-01T22:52:00+00:00, execution_date=20250701T225200, start_date=20250701T225401, end_date=20250701T225411
[2025-07-01T22:54:12.017+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 59 for task dbt_run_silver (Docker container failed: {'StatusCode': 1}; 413)
[2025-07-01T22:54:12.028+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-01T22:54:12.046+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-01T22:54:12.050+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
